### ISSUE TITLE
Testnet api issue

### ISSUE THREAD

**Issue by ghost** [steemit/dsteem#13]
I'm trying to use the live testnet node described here https://developers.steem.io/testnet/

but I'm getting the error "Invalid cast from type 'array_type' to Object" while trying using the comment command (trying to post something).

Here's my code using dsteem lib:

```
testnetApi = new dsteem.Client('https://testnet.steemitdev.com', {
    chainId: '46d82ab7d8db682eb1959aed0ada039a6d49afa1602491f93dde9cac3e8e6c32',
    prefix: 'TST'
});
testnetDSapi.broadcast.comment(article, key);
```

article object:

```
    article.parent_author = '';
    article.title = 'blablah';                
    article.author = username;
    article.parent_permlink = tags[0];
    article.permlink = 'valid_permlink'
    article.json_metadata = JSON.stringify({
        tags: tags
     });
```

**Comment by relativityboy** [comment]
What version of dsteem are you using?

**Comment by ghost** [comment]
@relativityboy I was using dsteem 0.9. Updated to 0.10.1 and the error is gone. ty.
